### ISSUE TITLE
 No such file or directory @ rb_sysopen - html/../sre-book/chapters/foreword (Errno::ENOENT)

### ISSUE THREAD

**Issue by sudipidus** [captn3m0/google-sre-ebook#23] opened 2019-03-15 05:52 UTC
I tried to get the docker container running but this is what I get:

Converted links in 50 files in 0.09 seconds.
generate.rb:14:in `initialize': No such file or directory @ rb_sysopen - html/../sre-book/chapters/foreword (Errno::ENOENT)
	from generate.rb:14:in `open'
	from generate.rb:14:in `block in <main>'
	from generate.rb:11:in `each'
	from generate.rb:11:in `<main>'
/src/bootstrap.sh: line 20: pushd: html/chapters: No such file or directory
pandoc: ../../metadata.xml: openFile: does not exist (No such file or directory)
/src/bootstrap.sh: line 22: popd: directory stack empty
Cannot read from /src/google-sre.epub
chown: cannot access 'google-sre.*': No such file or directory
failed to change ownership of 'google-sre.*' to 0:0
mv: cannot stat 'google-sre.*': No such file or directory

**Comment by captn3m0** [comment] 2019-03-18 12:51
Can you give the exact command you used please?

**Comment by sudipidus** [comment] 2019-03-18 12:54
@captn3m0 docker run --rm --volume "$(pwd):/output" -e BOOK_SLUG='srw_book' captn3m0/google-sre-ebook:latest (from readme)

**Comment by sudipidus** [comment] 2019-03-18 12:57
Also, I have a suggestion. Can you keep biweekly copies of ebooks created in the repo? That would be useful for people  who would have trouble setting up the project (or want a quick download)

**Comment by captn3m0** [comment] 2019-03-18 13:04
I was under the assumption that this would likely violate copyright, but it looks like Google has licensed them under [cc-by-nc-nd](https://creativecommons.org/licenses/by-nc-nd/4.0/).

Might be possible.

What platform are you running the command on? I just ran it and it worked fine for me. The output is confusing because you are calling it with `srw_book` and the error refers to `sre-book`

**Comment by sudipidus** [comment] 2019-03-18 13:09
I am getting same error for both `sre_book` and `srw_book`
Platform: `ubuntu 18.10 (Cosmic Cuttlefish)`

Would you be kind enough to mail me those copies [sudip.post@gmail.com] ?

**Comment by captn3m0** [comment] 2019-03-18 16:49
Created a release with files: https://github.com/captn3m0/google-sre-ebook/releases/tag/2019-03-18

I cannot reproduce the issue, this is likely a connectivity issue, so closing this.

**Closed as completed by captn3m0** 2019-03-18 16:49 UTC
