### ISSUE TITLE
Table malformation in Appendix A of Site Reliability Engineering book

### ISSUE THREAD

**Issue by elmanytas** [captn3m0/google-sre-ebook#35] opened 2020-10-07 14:47 UTC
Very good work with the conversion!!!

I found a little problem in [Appendix A of Site Reliability Engineering](https://landing.google.com/sre/sre-book/chapters/availability-table/) where the table is malformed:
![Captura de pantalla -2020-10-07 16-45-13](https://user-images.githubusercontent.com/1902658/95346856-8e58f300-08bc-11eb-8d0b-b255e53ae785.png)

**Comment by danielrheinbay** [comment] 2021-11-18 20:05
Duplicate of #34?

**Comment by captn3m0** [comment] 2021-11-19 06:36
Yup, closing this one.

**Closed as completed by captn3m0** 2021-11-19 06:36 UTC
